spring.datasource.url=jdbc:postgresql://dpg-d6en9b15pdvs73d16rmg-a:5432/tractor_management_db
spring.datasource.username=tractor_management_db_user
spring.datasource.password=u9HJZAbx4t6gGuUIBMq1p4Vu4RtI8mMb

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}